### ISSUE TITLE
Error to find file with read.dbc

### ISSUE THREAD

**Issue by leandrobi** [danicat/read.dbc#10]
Hi,
I used setwd("C:/Users/leand/Desktop/dbc") for set the path with my files
After, I put library("read.dbc") but when I try to pass for the row with x <- read.dbc(system.file("PASC2007.dbc")), I'm receiving this message: Error in dbc2dbf(file, out) : Input file does not exist.

In the folder, the file is there.

**Code:**
setwd("C:/Users/leand/Desktop/dbc")

library("read.dbc")
x <- read.dbc(system.file("PASC2007.dbc"))
str(x)

**Console:**
> setwd("C:/Users/leand/Desktop/dbc")
> library("read.dbc")
> x <- read.dbc(system.file("PASC2007.dbc"))
Error in dbc2dbf(file, out) : Input file does not exist.

**Comment by CauanCabral** [comment]
I had the same issue following manual instructions, but it is our fault.

The `system.file()` usage in manual is to enable a _demo_ with packaged **dbc** files.

To load file from local path, we should pass it name directly to `read.dbc` function:

```R
x <- read.dbc("PASC2007.dbc")
```

**Comment by danicat** [comment]
@CauanCabral yes, the example in the documentation must be runnable by CRAN's standards, so that is designed for the internal tests to pass. In the real world you most likely won't want to use `system.file`.
