### ISSUE TITLE
Package removal from CRAN - read.dbc

### ISSUE THREAD

**Issue by GleytonLima** [danicat/read.dbc#11]
Hello,

I noticed that the read.dbc package has been removed from the CRAN repository due to a policy violation (https://cran.r-project.org/web/packages/read.dbc/index.html). I was hoping to use this package for my project, but it seems that it is no longer available through the standard R channels. I would like to know the reason for the policy violation and if there are any plans to address it and bring the package back to CRAN.

In the meantime, I also noticed that the package is still available on Github. Is it safe to use this package from Github, or are there any known issues that I should be aware of?

Thank you for your time and help in this matter.

**Comment by eroubenoff** [comment]
Hello, I am trying to use this package as well and am unable to install from CRAN.

**Comment by beatrizmilz** [comment]
@eroubenoff You can install from GitHub using:
```
devtools::install_github("danicat/read.dbc")
```
@danicat Hi Dani! Do you plan to add the package to CRAN again?

**Comment by bc-teixeira** [comment]
@lcgrossi 
It is likely you need to install the Rtools version compatible with your current R version.
https://cran.r-project.org/bin/windows/Rtools/

**Comment by danicat** [comment]
Hi everyone, I'm really sorry for the long wait. Today I finally had some time and applied the fixes necessary to resubmit the package to CRAN. It will take a while before they review it but hopefully it will be available over the next few days.

**Comment by beatrizmilz** [comment]
Thanks @danicat !

**Comment by rfsaldanha** [comment]
Already on CRAN !!

**Comment by beatrizmilz** [comment]
Thanks @danicat !!

**Comment by GleytonLima** [comment]
Thanks @danicat! Already on CRAN as we can see in https://cran.r-project.org/web/packages/read.dbc/index.html. So i will close this issue, thanks!

**Comment by danicat** [comment]
Again sorry everyone for the trouble. To give you a bit more options just in case stuff happens again, now we have a python version: https://github.com/danicat/pysus

Still experimental, but I'll add pandas support very soon. For now you can use it to decompress DBC files from the command line or from a python script.
