### ISSUE TITLE
Error using read.dbc 

### ISSUE THREAD

**Issue by lego-yaw** [danicat/read.dbc#16]
I am truing to use read.dbc to read this file i downloaded form datasus but i keep getting this error.
file1 <- read.dbc("ABOSP2201.dbc")
Error in read.dbc("ABOSP2201.dbc") : 
  error decompressing file: -1

can you tell me why this is happening

**Comment by filipemsc** [comment]
I am having the same error

**Comment by lego-yaw** [comment]
I actually realized I downloaded the file without the (.dbc) at the end of the string and that was giving me the problems, I don’t know if it is the same thing happening to you..try checking that and see ..
