### ISSUE TITLE
Blast error code: -3

### ISSUE THREAD

**Issue by brenoea** [danicat/read.dbc#3]
Dani,

I tried to replicate the usage procedure as described in readme.me. As soon as I ran the read.dbc function, I got the following error:  blast error code: -3

 I'm using R version 3.3.1 under windows 64 bit

**Comment by danicat** [comment]
This error code suggests that the dbc file is corrupted. I would suggest you to try downloading the file again and retry. If that doesn't work, could you please provide some sample code that reproduces the problem?

**Comment by brenoea** [comment]
Dani,

You were completely right. For some unknown reason my download.file function keeps corrupting the files.  Thank you. It´s an amazing package. Congrats.
