### ISSUE TITLE
Closing connection in corrupted files

### ISSUE THREAD

**Issue by DanielFerrazCampos** [danicat/read.dbc#4]
Hi danicat!

I have been using read.dbc function from read.dbc package and it is working fine for me (btw, **thank you very much** for that contribution!).

Unfortunatelly, sometimes the file to be read is corrupted. To handle this, I use the try statement. The problem is that the corrupted file keeps "open" in R until I finish my R session, in a way I can't delete the file until the session is over.

My code is:

`ReadFile <- try(read.dbc("C:/LocalPath/A_File.txt"))`

Is there a way to "close" the connection prematurely (without the need to end the session)?

More details: RStudio v0.99.484, R v3.3.1 (x64), OS Windows 7 Enterprise SP1

PS.: To reproduce the error simply try to read any file that is not a dbc file, a TXT file for example.

UPDATE:
[AEF](http://stackoverflow.com/users/6664578/aef) from [Stackoverflow](http://stackoverflow.com/questions/39516504/how-to-close-file-connection-in-r-after-an-error-handle) made a contribution that might help.

**Comment by danicat** [comment]
Hi Daniel. First of all thanks for your feedback :)

I've did a quick inspection of the C code handling the file I/O and I've found the bug. I'll provide a fix for the development version as soon as possible. Thanks for pointing this out.

**Comment by danicat** [comment]
Daniel, I've submitted a fix to the development version. Could you test it please?

**Comment by DanielFerrazCampos** [comment]
Daniela, it works perfectly and also suggests that the file might be corrupted:

`Error in dbc2dbf(file, out) : Corrupted file? Blast error code: 2`

This solves the issue I have pointed out.

**Comment by danicat** [comment]
I've changed the error message because this seem to be a common error and I thought it would be an useful hint. :)

Thanks for testing. I'll publish it to CRAN later today.

**Comment by DanielFerrazCampos** [comment]
Perfect! Looking forward for the release.

**Comment by danicat** [comment]
Done! It may take a while to be published though. It must first pass all the system tests to be released. Probably in a couple of days or so it will be available for everybody.
