### ISSUE TITLE
Error: could not find function "read.dbc"

### ISSUE THREAD

**Issue by pavoltravnik** [danicat/read.dbc#5]
in R for Mac I used 
`install.packages("read.dbc")`
and then 
`x <- read.dbc(system.file("/Users/username/Downloads/DNRAC94.DBC", package="read.dbc"))`

a result was
`Error: could not find function "read.dbc"`

Could you clarify, what I did wrong? Thank you a lot.

**Comment by danicat** [comment]
You need to load the package first with the commad `library`. For example:

```
library("read.dbc")
x <- read.dbc(system.file("/Users/username/Downloads/DNRAC94.DBC"))
```

Please let me know if it works for you.

**Comment by pavoltravnik** [comment]
With this it works perfectly fine! Thank you.

**Comment by danicat** [comment]
Great!
