### ISSUE TITLE
add stringsAsFactors = F functionality

### ISSUE THREAD

**Issue by lucasmation** [danicat/read.dbc#6]
The package is great. 
For the SIM data, all the variables are imported as factor variables. 
It would be nice to add the "stringsAsFactors", so that people can turn that behavior off (stringsAsFactors = F)

**Comment by michelbieleveld** [comment]
This is already possible. Just supply as.is=TRUE as an addition parameter when you open the file;

dbc.read(filename, as.is=TRUE)

**Comment by danicat** [comment]
Thanks for that information @michelbieleveld. It has been a while since I last worked on it so I didn't remember that option. Since we are using `read.dbf` on the background (after decompression) any parameter allowed for `read.dbf` is also allowed for `read.dbc`.
